[project]
name = "tldraw"
version = "0.1.0"
description = "Tldraw project"
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
start = "jupyter lab"

[dependencies]
python = "3.12.0.*"
numpy = "1.26.2.*"
jupyterlab-myst = "2.1.0.*"
matplotlib = "3.8.2.*"
jupyterlab = "4.0.9.*"
scipy = "1.11.4.*"

[pypi-dependencies]
perfect-freehand = "==1.2.0"
